#!/bin/bash
# Builds "Girl Math.app" — a macOS app bundle that launches the server and
# opens the browser. Drag the result to /Applications or the Dock.
#
#   ./scripts/make-app.sh
#
# The bundle records where this project lives, so re-run it if you move
# the project folder.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP="$PROJECT_DIR/build/Girl Math.app"

cd "$PROJECT_DIR"

echo "Drawing the icon..."
node scripts/make-icon.mjs

rm -rf build/icon.iconset
mkdir -p build/icon.iconset
for s in 16 32 128 256 512; do
  sips -z "$s" "$s" build/icon.png --out "build/icon.iconset/icon_${s}x${s}.png" > /dev/null 2>&1
  sips -z "$((s * 2))" "$((s * 2))" build/icon.png --out "build/icon.iconset/icon_${s}x${s}@2x.png" > /dev/null 2>&1
done
iconutil -c icns build/icon.iconset -o build/icon.icns

echo "Assembling the bundle..."
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp build/icon.icns "$APP/Contents/Resources/icon.icns"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>                  <string>Girl Math</string>
  <key>CFBundleDisplayName</key>           <string>Girl Math</string>
  <key>CFBundleIdentifier</key>            <string>io.github.trishatjokro.girlmath</string>
  <key>CFBundleExecutable</key>            <string>girlmath</string>
  <key>CFBundleIconFile</key>              <string>icon</string>
  <key>CFBundlePackageType</key>           <string>APPL</string>
  <key>CFBundleVersion</key>               <string>1.0</string>
  <key>CFBundleShortVersionString</key>    <string>1.0</string>
  <key>LSMinimumSystemVersion</key>        <string>11.0</string>
  <key>NSHighResolutionCapable</key>       <true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/girlmath" <<LAUNCHER
#!/bin/bash
# Launcher generated by scripts/make-app.sh — re-run that to regenerate.
#
# This starts the server detached and exits straight away. It must not block:
# macOS expects a double-clicked .app to check in with the window server, and
# a launcher that sits in the foreground gets reported as "not responding".

PROJECT_DIR="$PROJECT_DIR"
export PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"

LOG="\$HOME/Library/Logs/GirlMath.log"
mkdir -p "\$(dirname "\$LOG")"

fail() {
  echo "\$(date): \$1" >> "\$LOG"
  osascript -e "display alert \"Girl Math\" message \"\$1\""
  exit 1
}

cd "\$PROJECT_DIR" || fail "The project folder has moved. Re-run scripts/make-app.sh to point the app at its new location."

command -v node > /dev/null 2>&1 || fail "Node isn't installed. Open Terminal and run: brew install node"

PORT="\${PORT:-3000}"

# Already running? Just bring the tab up rather than starting a second copy.
if curl -s -o /dev/null "http://localhost:\$PORT/" 2>/dev/null; then
  open "http://localhost:\$PORT/"
  exit 0
fi

if [ ! -d node_modules ]; then
  echo "\$(date): installing dependencies" >> "\$LOG"
  npm install >> "\$LOG" 2>&1 || fail "Couldn't install dependencies. See ~/Library/Logs/GirlMath.log"
fi

# Detach the server so it outlives this launcher process.
nohup npm start >> "\$LOG" 2>&1 &
disown

# Open the browser once the server actually answers, in a background subshell
# so the launcher itself can exit now.
(
  for _ in \$(seq 1 60); do
    if curl -s -o /dev/null "http://localhost:\$PORT/" 2>/dev/null; then
      open "http://localhost:\$PORT/"
      exit 0
    fi
    sleep 0.25
  done
  echo "\$(date): server never came up" >> "\$LOG"
) &
disown

exit 0
LAUNCHER

chmod +x "$APP/Contents/MacOS/girlmath"

# Nudge Finder to notice the new icon rather than caching the generic one.
touch "$APP"

echo
echo "Built: $APP"
echo "Drag it to /Applications or your Dock."
